#!/usr/bin/env bash
# A Bash script that stops the 4-to_infinity_and_beyond process

# Find the PID(s) of the 4-to_infinity_and_beyond script
PID=$(pgrep -f 4-to_infinity_and_beyond)

# Kill the process
if [ -n "$PID" ]; then
    kill "$PID"
fi
